// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWFtBRzOt9PIZlSH8XOOZOkowy1xu6p4',
    appId: '1:1091279801798:web:078afa9570765942d7b6c7',
    messagingSenderId: '1091279801798',
    projectId: 'fruit-hub-2ca62',
    authDomain: 'fruit-hub-2ca62.firebaseapp.com',
    storageBucket: 'fruit-hub-2ca62.firebasestorage.app',
    measurementId: 'G-3E2VH0GZ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDclhCEIuUIe8J_CfUKQU1Dz5xoxBrk-Sk',
    appId: '1:1091279801798:android:63be480b758b6009d7b6c7',
    messagingSenderId: '1091279801798',
    projectId: 'fruit-hub-2ca62',
    storageBucket: 'fruit-hub-2ca62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeoNWLFW2NEqpXxFcqldI9lBcp7QP9W-8',
    appId: '1:1091279801798:ios:395d1fa3f4e8d837d7b6c7',
    messagingSenderId: '1091279801798',
    projectId: 'fruit-hub-2ca62',
    storageBucket: 'fruit-hub-2ca62.firebasestorage.app',
    androidClientId: '1091279801798-a14i4okefp97n9dju4jln2hs1fa3mq07.apps.googleusercontent.com',
    iosClientId: '1091279801798-invth182t7khoe1si98irbl4gomjkne7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeoNWLFW2NEqpXxFcqldI9lBcp7QP9W-8',
    appId: '1:1091279801798:ios:395d1fa3f4e8d837d7b6c7',
    messagingSenderId: '1091279801798',
    projectId: 'fruit-hub-2ca62',
    storageBucket: 'fruit-hub-2ca62.firebasestorage.app',
    androidClientId: '1091279801798-a14i4okefp97n9dju4jln2hs1fa3mq07.apps.googleusercontent.com',
    iosClientId: '1091279801798-invth182t7khoe1si98irbl4gomjkne7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAWFtBRzOt9PIZlSH8XOOZOkowy1xu6p4',
    appId: '1:1091279801798:web:0e349ea8c3a7a1dfd7b6c7',
    messagingSenderId: '1091279801798',
    projectId: 'fruit-hub-2ca62',
    authDomain: 'fruit-hub-2ca62.firebaseapp.com',
    storageBucket: 'fruit-hub-2ca62.firebasestorage.app',
    measurementId: 'G-1NHED11WX1',
  );
}
